### ISSUE TITLE
How do I report an issue against tap-spec?

### ISSUE THREAD

**Issue by brenthompson** [frncsdrk/frncsdrk#1]
Hi, and sorry to bother you on your "personal" GH site. There's an issue with tap-spec v5.0.4, but there's no way to report an issue against it or tap-out. Let me know how you wish to receive details of the issue. Thanks,

**Comment by frncsdrk** [comment]
Oh, sorry about that and thanks for asking. That's probably because the repo is a fork.
You can open an issue [here](https://github.com/randomgoods/issues).
